# common definitions

CC       =gcc
CPP      =gcc -E
PRJCFLAGS=-g
LD       =gcc
LDCONFIG =ldconfig
LDFLAGS  =
LDSHARED =gcc
LDSHAREDLIBC=-lc
AR       =ar rc
ARFLAGS  =
RANLIB   =ranlib
RM       =rm
ECHO     =echo

TAR      =tar
SHELL    =/bin/sh
EXE      =
MAKE     =make

#.SILENT :

